- name: Build APK with Buildozer
      run: |
        export MAKEFLAGS="-j1"
        buildozer -v android debug || true
        cat .buildozer/android/platform/build-*/build/other_builds/*/*/puppet/build.log || true
        cat .buildozer/android/platform/build-*/dists/*/__build.log || true
